  config_stream << "<?xml version=\"1.0\" encoding=\"utf-8\"?>";
  config_stream << "<af>";
  config_stream << "	<gain>27</gain>";
  config_stream << "	<bw>2</bw>";
  config_stream << "</af>";
  config_stream << "<rx>";
  config_stream << "	<mode>NBFM</mode>";
  config_stream << "	<freq>162550000.0</freq>";
  config_stream << "	<prev_freq>162450000.0</prev_freq>";
  config_stream << "</rx>";
  config_stream << "<tx>";
  config_stream << "	<freq>146520000.0</freq>";
  config_stream << "	<prev_freq>0</prev_freq>";
  config_stream << "	<rf_outpower>0.0</rf_outpower>";
  config_stream << "	<tx_rx_locked>false</tx_rx_locked>";
  config_stream << "</tx>";
  config_stream << "<transverter>";
  config_stream << "	<base>";
  config_stream << "		<nominal>0</nominal>";
  config_stream << "		<actual>0</actual>";
  config_stream << "	</base>";
  config_stream << "	<lo>";
  config_stream << "		<mult>0</mult>";
  config_stream << "	</lo>";
  config_stream << "</transverter>";
  config_stream << "<station>";
  config_stream << "	<call/>";
  config_stream << "	<qth/>";
  config_stream << "</station>";
  config_stream << "<cw>";
  config_stream << "	<speed>10</speed>";
  config_stream << "	<sidetone>20</sidetone>";
  config_stream << "</cw>";
  config_stream << "<spectrum>";
  config_stream << "	<center_freq>162555000</center_freq>";
  config_stream << "	<yscale>10</yscale>";
  config_stream << "	<bandspread>200000</bandspread>";
  config_stream << "	<reflevel>0</reflevel>";
  config_stream << "	<display>waterfall</display>";
  config_stream << "</spectrum>";
  config_stream << "<reference>";
  config_stream << "	<source>true</source>";
  config_stream << "</reference>";
