SoDaRadio-5.0.1-master:9075e65: GUISoDa::BandMap Class Reference
GUISoDa::BandMap Class Reference
#include <soda_band.hpp>
Public Types
typedef QMapIterator< QString, Band > BandMapIterator
Public Member Functions
BandMap ()
void restoreBands (QSettings *set_p)
void saveBands (QSettings *set_p)
QString findBand (double freq) const
Detailed Description
Definition at line 141 of file soda_band.hpp.
Member Typedef Documentation
BandMapIterator
typedef QMapIterator<QString, Band> GUISoDa::BandMap::BandMapIterator
Definition at line 145 of file soda_band.hpp.
Constructor & Destructor Documentation
BandMap()
GUISoDa::BandMap::BandMap () inline
Definition at line 143 of file soda_band.hpp.
Member Function Documentation
findBand()
QString GUISoDa::BandMap::findBand (double freq) const inline
Definition at line 174 of file soda_band.hpp.
Referenced by MainWindow::updateBandDisplay().
restoreBands()
void GUISoDa::BandMap::restoreBands (QSettings * set_p) inline
Definition at line 147 of file soda_band.hpp.
References GUISoDa::Band::name(), and GUISoDa::Band::restore().
Referenced by MainWindow::bandMapSaveRestore().
saveBands()
void GUISoDa::BandMap::saveBands (QSettings * set_p) inline
Definition at line 160 of file soda_band.hpp.
Referenced by MainWindow::bandMapSaveRestore().
The documentation for this class was generated from the following file:
qtgui/soda_band.hpp