SoDaRadio-5.0.1-master:9075e65: GUISoDa::ValComboBox Class Reference
GUISoDa::ValComboBox Class Reference
#include <soda_comboboxes.hpp>
Public Slots
void addValue (QString lab, double val)
void setValue (double v)
Signals
void valueChanged (double v)
Public Member Functions
ValComboBox (QWidget *parent=0)
double value ()
Protected Member Functions
void textChanged (const QString &txt)
Protected Attributes
std::map< QString, double > valmap
Detailed Description
Definition at line 42 of file soda_comboboxes.hpp.
Constructor & Destructor Documentation
ValComboBox()
GUISoDa::ValComboBox::ValComboBox (QWidget * parent = 0) inline explicit
Definition at line 45 of file soda_comboboxes.hpp.
References textChanged().
Member Function Documentation
addValue
void GUISoDa::ValComboBox::addValue (QString lab, double val) slot
Definition at line 33 of file soda_comboboxes.cpp.
References valmap.
Referenced by value(), GUISoDa::IntValComboBox::value(), GUISoDa::WFallDynRangeComboBox::WFallDynRangeComboBox(), and GUISoDa::WFallSpanComboBox::WFallSpanComboBox().
setValue
void GUISoDa::ValComboBox::setValue (double v) slot
Definition at line 40 of file soda_comboboxes.cpp.
References valmap.
Referenced by value(), GUISoDa::IntValComboBox::value(), GUISoDa::WFallDynRangeComboBox::WFallDynRangeComboBox(), and GUISoDa::WFallSpanComboBox::WFallSpanComboBox().
textChanged()
void GUISoDa::ValComboBox::textChanged (const QString & txt) protected
Definition at line 55 of file soda_comboboxes.cpp.
References valmap, and valueChanged().
Referenced by ValComboBox(), value(), and GUISoDa::IntValComboBox::value().
value()
double GUISoDa::ValComboBox::value () inline
Definition at line 51 of file soda_comboboxes.hpp.
References addValue(), setValue(), textChanged(), valmap, and valueChanged().
valueChanged
void GUISoDa::ValComboBox::valueChanged (double v) signal
Referenced by textChanged(), GUISoDa::IntValComboBox::textChanged(), value(), and GUISoDa::IntValComboBox::value().
Member Data Documentation
valmap
std::map<QString, double> GUISoDa::ValComboBox::valmap protected
Definition at line 65 of file soda_comboboxes.hpp.
Referenced by addValue(), GUISoDa::IntValComboBox::addValue(), setValue(), GUISoDa::IntValComboBox::setValue(), textChanged(), GUISoDa::IntValComboBox::textChanged(), value(), and GUISoDa::IntValComboBox::value().
The documentation for this class was generated from the following files:
qtgui/soda_comboboxes.hpp
qtgui/soda_comboboxes.cpp