SoDaRadio-5.0.1-master:9075e65: SoDa::N200Control Class Reference
SoDa::N200Control Class Reference
Transmit/Receive switch control for N200/N210 via the GPS serial or EXP serial io port.
#include <N200Control.hxx>
Public Member Functions
N200Control (uhd::usrp::multi_usrp::sptr usrp, int mboard, std::string ip_addr_str, unsigned int portnum=49172)
constructor
bool setTXOn ()
activate external controls to enable transmit mode.
bool setTXOff ()
activate external controls to disable transmit mode.
bool getTX ()
report state of transmit-enable.
bool setBand (unsigned int band, bool state)
turn on/off signal path for selected band note that multiple bands can be enabled at one time(!)
bool getBand (unsigned int band)
query state of signal path for selected band
Public Member Functions inherited from SoDa::TRControl
TRControl ()
virtual bool setServo (unsigned int servo_sel, double val)
set state of selected servo
Private Member Functions
bool sendCommand (const std::string &cmd, int retry_count)
Private Attributes
IP::ClientSocket * skt
uhd::usrp::multi_usrp::sptr usrp
int mboard
Additional Inherited Members
Static Public Member Functions inherited from SoDa::TRControl
static TRControl * makeTRControl (uhd::usrp::multi_usrp::sptr usrp, int mboard=0)
make the appropriate TR control widget given a pointer to a USRP device.
Detailed Description
Transmit/Receive switch control for N200/N210 via the GPS serial or EXP serial io port.
(Default is GPS port).
Definition at line 48 of file N200Control.hxx.
Constructor & Destructor Documentation
N200Control()
SoDa::N200Control::N200Control (uhd::usrp::multi_usrp::sptr usrp, int mboard, std::string ip_addr_str, unsigned int portnum = 49172)
constructor
Parameters
usrp pointer to usrp multi dev
mboard motherboard index (0 is good)
ip_addr_str the ip address of the selected radio
portnum the port to use
Definition at line 48 of file N200Control.cxx.
References mboard, SoDa::IP::NetSocket::setBlocking(), setTXOff(), skt, SoDa::IP::UDP, and usrp.
Member Function Documentation
getBand()
bool SoDa::N200Control::getBand (unsigned int band) virtual
query state of signal path for selected band
Parameters
band band selector (typically index from 1...7)
Returns
true if band signal path is enabled.
Reimplemented from SoDa::TRControl.
Definition at line 128 of file N200Control.cxx.
getTX()
bool SoDa::N200Control::getTX () virtual
report state of transmit-enable.
Returns
true iff the transmitter is currently enabled.
Implements SoDa::TRControl.
Definition at line 121 of file N200Control.cxx.
sendCommand()
bool SoDa::N200Control::sendCommand (const std::string & cmd, int retry_count) private
setBand()
bool SoDa::N200Control::setBand (unsigned int band, bool state) virtual
turn on/off signal path for selected band note that multiple bands can be enabled at one time(!)
Parameters
band band selector (typically index from 1...7)
state true to enable band, false otherwise.
Returns
true if band state was changed.
Reimplemented from SoDa::TRControl.
Definition at line 126 of file N200Control.cxx.
setTXOff()
bool SoDa::N200Control::setTXOff () virtual
activate external controls to disable transmit mode.
Returns
true if the operation completed successfully
Implements SoDa::TRControl.
Definition at line 97 of file N200Control.cxx.
References SoDa::IP::NetSocket::getRaw(), SoDa::IP::NetSocket::putRaw(), and skt.
Referenced by N200Control().
setTXOn()
bool SoDa::N200Control::setTXOn () virtual
activate external controls to enable transmit mode.
Returns
true if the operation completed successfully
Implements SoDa::TRControl.
Definition at line 73 of file N200Control.cxx.
References SoDa::IP::NetSocket::getRaw(), SoDa::IP::NetSocket::putRaw(), and skt.
Member Data Documentation
mboard
int SoDa::N200Control::mboard private
Definition at line 108 of file N200Control.hxx.
Referenced by N200Control().
skt
IP::ClientSocket* SoDa::N200Control::skt private
Definition at line 102 of file N200Control.hxx.
Referenced by N200Control(), setTXOff(), and setTXOn().
usrp
uhd::usrp::multi_usrp::sptr SoDa::N200Control::usrp private
Definition at line 107 of file N200Control.hxx.
Referenced by N200Control().
The documentation for this class was generated from the following files:
src/N200Control.hxx
src/N200Control.cxx