SoDaRadio-5.0.1-master:9075e65: exp/LineSockets_Test.cxx File Reference
LineSockets_Test.cxx File Reference
#include "LineSocket.hxx"
#include <error.h>
#include <stdio.h>
Functions
void usage ()
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 40 of file LineSockets_Test.cxx.
References SoDa::IP::LineServerSocket::getLine(), SoDa::IP::ServerSocket::isReady(), and usage().
usage()
void usage ()
Definition at line 33 of file LineSockets_Test.cxx.
Referenced by main().