SoDaRadio-5.0.1-master:9075e65: qtgui/main_sodaradio.cpp File Reference
main_sodaradio.cpp File Reference
#include "mainwindow.hpp"
#include <QApplication>
#include <iostream>
#include <QMessageBox>
#include <QStyleFactory>
#include <QTextStream>
#include <QDir>
#include "../common/GuiParams.hxx"
#include <stdlib.h>
Functions
static QString ss2QS (const std::string &st)
simple conversion from std::string to QString...
static void alertAndExit (const QString &err_msg)
pop up a notification box and then bail out.
static void startupServer (const QString &lock_file_name, SoDa::GuiParams &p)
start the radio server process
void setupLookNFeel ()
initialize colors and shades for GUI elements to present a look and feel based on the fusion style, but with dark background.
bool checkForZombies (const QString &server_lock_filename, const QString &server_socket_base)
int main (int argc, char *argv[])
Start the SoDaRadio GUI app and launch the server process.
Function Documentation
alertAndExit()
static void alertAndExit (const QString & err_msg) static
pop up a notification box and then bail out.
Parameters
err_msg a descriptive message explaining how we got here.
Definition at line 55 of file main_sodaradio.cpp.
Referenced by startupServer().
checkForZombies()
bool checkForZombies (const QString & server_lock_filename, const QString & server_socket_base)
Definition at line 144 of file main_sodaradio.cpp.
Referenced by main().
main()
int main (int argc, char * argv[])
Start the SoDaRadio GUI app and launch the server process.
Parameters
argc count of command line args
argv vector of command line tokens
Definition at line 187 of file main_sodaradio.cpp.
References checkForZombies(), setupLookNFeel(), and startupServer().
setupLookNFeel()
void setupLookNFeel ()
initialize colors and shades for GUI elements to present a look and feel based on the fusion style, but with dark background.
code borrowed from https://gist.github.com/skyrpex under his "do whatever you want" license
Definition at line 119 of file main_sodaradio.cpp.
Referenced by main().
ss2QS()
static QString ss2QS (const std::string & st) static
simple conversion from std::string to QString...
Parameters
st std::string
Returns
a QString corresponding to the input parameter
Definition at line 45 of file main_sodaradio.cpp.
Referenced by startupServer().
startupServer()
static void startupServer (const QString & lock_file_name, SoDa::GuiParams & p) static
start the radio server process
Parameters
p set of command line parameters, some of which are passed to the server process.
Definition at line 71 of file main_sodaradio.cpp.
References alertAndExit(), and ss2QS().
Referenced by main().