SoDaRadio-5.0.1-master:9075e65: exp/ReSampler_Test.cxx File Reference
ReSampler_Test.cxx File Reference
#include <complex>
#include <iostream>
#include <fstream>
#include <stdlib.h>
#include "ReSampler.hxx"
#include "ReSamplers625x48.hxx"
#include <time.h>
#include <fftw3.h>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
Macros
#define SAMPLE_RATE 48000
Functions
double curtime ()
static void bindump (char *fn, std::complex< float > *buf, unsigned int num_elts) __attribute__((unused))
void checkResult (FILE *ofile, float anginc, unsigned int iM, unsigned int dN, unsigned int inlen, std::complex< float > *invec, std::complex< float > *outvec, int idx=0)
float loadVector (float ang, float ang_inc, std::complex< float > *vec, int len)
void test625x48 ()
void test48x625 ()
void aliasingPlot ()
int main (int argc, char *argv[])
Macro Definition Documentation
SAMPLE_RATE
#define SAMPLE_RATE 48000
Definition at line 28 of file ReSampler_Test.cxx.
Function Documentation
aliasingPlot()
void aliasingPlot ()
Definition at line 160 of file ReSampler_Test.cxx.
References SoDa::ReSample625to48::apply().
Referenced by main().
bindump()
static void bindump (char * fn, std::complex< float > * buf, unsigned int num_elts) static
Definition at line 62 of file ReSampler_Test.cxx.
Referenced by curtime().
checkResult()
void checkResult (FILE * ofile, float anginc, unsigned int iM, unsigned int dN, unsigned int inlen, std::complex< float > * invec, std::complex< float > * outvec, int idx = 0)
Definition at line 73 of file ReSampler_Test.cxx.
Referenced by main().
curtime()
double curtime ()
Definition at line 52 of file ReSampler_Test.cxx.
References bindump().
Referenced by main().
loadVector()
float loadVector (float ang, float ang_inc, std::complex< float > * vec, int len)
Definition at line 110 of file ReSampler_Test.cxx.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 207 of file ReSampler_Test.cxx.
References aliasingPlot(), SoDa::ReSampler::apply(), checkResult(), curtime(), loadVector(), test48x625(), and test625x48().
test48x625()
void test48x625 ()
Definition at line 156 of file ReSampler_Test.cxx.
Referenced by main().
test625x48()
void test625x48 ()
Definition at line 123 of file ReSampler_Test.cxx.
References SoDa::ReSample625to48::apply().
Referenced by main().