SoDaRadio-5.0.1-master:9075e65: exp/Audio_test.cxx File Reference
Audio_test.cxx File Reference
#include <math.h>
#include "AudioALSA.hxx"
#include "AudioPA.hxx"
#include <iostream>
#include <time.h>
Macros
#define CAPSAMPS (48 * 1000 * 5)
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
CAPSAMPS
#define CAPSAMPS (48 * 1000 * 5)
Referenced by main().
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 6 of file Audio_test.cxx.
References CAPSAMPS, SoDa::AudioIfc::FLOAT, SoDa::AudioIfc::recv(), SoDa::AudioIfc::recvBufferReady(), SoDa::AudioIfc::send(), SoDa::AudioIfc::sendBufferReady(), SoDa::AudioIfc::setOutGain(), SoDa::AudioIfc::sleepIn(), and SoDa::AudioIfc::wakeIn().