SoDaRadio-5.0.3-master:8901fb5: GUISoDa::HamlibServer Class Reference
GUISoDa::HamlibServer Class Reference
#include <soda_hamlib_server.hpp>
Public Slots
bool start ()
Signals
void stopListeners ()
Public Member Functions
HamlibServer (QObject *parent=0, int _port_num=4575)
~HamlibServer ()
HamlibHandler * getHandler ()
Protected Member Functions
void incomingConnection (qintptr desc)
Protected Attributes
int port_num
HamlibHandler * handler_p
std::list< HamlibListener * > listener_list
Detailed Description
Definition at line 47 of file soda_hamlib_server.hpp.
Constructor & Destructor Documentation
HamlibServer()
GUISoDa::HamlibServer::HamlibServer (QObject * parent = 0, int _port_num = 4575)
Definition at line 40 of file soda_hamlib_server.cpp.
References handler_p.
~HamlibServer()
GUISoDa::HamlibServer::~HamlibServer ()
Definition at line 46 of file soda_hamlib_server.cpp.
References listener_list, and stopListeners().
Member Function Documentation
getHandler()
HamlibHandler* GUISoDa::HamlibServer::getHandler () inline
Definition at line 55 of file soda_hamlib_server.hpp.
References handler_p, incomingConnection(), start(), and stopListeners().
Referenced by MainWindow::setupHamlib().
incomingConnection()
void GUISoDa::HamlibServer::incomingConnection (qintptr desc) protected
Definition at line 61 of file soda_hamlib_server.cpp.
References handler_p, listener_list, and stopListeners().
Referenced by getHandler().
start
bool GUISoDa::HamlibServer::start () slot
Definition at line 55 of file soda_hamlib_server.cpp.
References port_num.
Referenced by getHandler(), and MainWindow::MainWindow().
stopListeners
void GUISoDa::HamlibServer::stopListeners () signal
Referenced by getHandler(), incomingConnection(), and ~HamlibServer().
Member Data Documentation
handler_p
HamlibHandler* GUISoDa::HamlibServer::handler_p protected
Definition at line 69 of file soda_hamlib_server.hpp.
Referenced by getHandler(), HamlibServer(), and incomingConnection().
listener_list
std::list<HamlibListener *> GUISoDa::HamlibServer::listener_list protected
Definition at line 71 of file soda_hamlib_server.hpp.
Referenced by incomingConnection(), and ~HamlibServer().
port_num
int GUISoDa::HamlibServer::port_num protected
Definition at line 67 of file soda_hamlib_server.hpp.
Referenced by start().
The documentation for this class was generated from the following files:
qtgui/soda_hamlib_server.hpp
qtgui/soda_hamlib_server.cpp