SoDaRadio-5.0.1-master:9075e65: GUISoDa::IntValComboBox Class Reference
GUISoDa::IntValComboBox Class Reference
#include <soda_comboboxes.hpp>
Public Slots
void addValue (QString lab, int val)
void setValue (int v)
void setValue (const QString &s)
Signals
void valueChanged (int v)
Public Member Functions
IntValComboBox (QWidget *parent=0)
int value ()
Protected Member Functions
void textChanged (const QString &txt)
Protected Attributes
std::map< QString, int > valmap
Detailed Description
Definition at line 100 of file soda_comboboxes.hpp.
Constructor & Destructor Documentation
IntValComboBox()
GUISoDa::IntValComboBox::IntValComboBox (QWidget * parent = 0) inline explicit
Definition at line 103 of file soda_comboboxes.hpp.
References textChanged().
Member Function Documentation
addValue
void GUISoDa::IntValComboBox::addValue (QString lab, int val) slot
Definition at line 61 of file soda_comboboxes.cpp.
References GUISoDa::ValComboBox::valmap.
setValue [1/2]
void GUISoDa::IntValComboBox::setValue (int v) slot
Definition at line 68 of file soda_comboboxes.cpp.
References GUISoDa::ValComboBox::valmap.
setValue [2/2]
void GUISoDa::IntValComboBox::setValue (const QString & s) slot
Definition at line 78 of file soda_comboboxes.cpp.
textChanged()
void GUISoDa::IntValComboBox::textChanged (const QString & txt) protected
Definition at line 89 of file soda_comboboxes.cpp.
References GUISoDa::ValComboBox::valmap, and GUISoDa::ValComboBox::valueChanged().
Referenced by IntValComboBox().
value()
int GUISoDa::IntValComboBox::value () inline
Definition at line 109 of file soda_comboboxes.hpp.
References GUISoDa::ValComboBox::addValue(), GUISoDa::ValComboBox::setValue(), GUISoDa::ValComboBox::textChanged(), GUISoDa::ValComboBox::valmap, and GUISoDa::ValComboBox::valueChanged().
valueChanged
void GUISoDa::IntValComboBox::valueChanged (int v) signal
Member Data Documentation
valmap
std::map<QString, int> GUISoDa::IntValComboBox::valmap protected
Definition at line 125 of file soda_comboboxes.hpp.
The documentation for this class was generated from the following files:
qtgui/soda_comboboxes.hpp
qtgui/soda_comboboxes.cpp