SoDaRadio-5.0.3-master:8901fb5: GUISoDa::WFall Class Reference
GUISoDa::WFall Class Reference
#include <soda_wfall.hpp>
Public Slots
void updateData (double cf, float *y)
void pickPoint (const QPointF &pos)
void setFreqMarker (double freq)
void setDynamicRange (double drange)
void setRefLevel (int rlvl)
void setFreqCenter (double cf, bool check_boundary=false)
void setFreqSpan (double fs, bool check_boundary=false)
void setFreqSpanKHz (double fs)
void scrollRight (bool v)
void scrollLeft (bool v)
void configureSpectrum (double cfreq, double span, long buckets)
void setMarkerOffset (double lo, double hi)
Signals
void xClick (double x)
Public Member Functions
WFall (QWidget *parent=0)
~WFall ()
double freqCenter ()
Protected Member Functions
double correctCenterFreq (double cfreq)
Protected Attributes
double center_freq
double freq_span
double spectrum_input_span
double last_input_cfreq
double marker_freq
WFallData * wfall_data
PlotSpectrogram * sgram
WFallPicker * picker_p
FreqScaleDraw * freq_scale_p
QwtScaleWidget * right_axis
Private Member Functions
void setZAxis ()
void setMarkers (double lo, double hi)
void initPlot ()
Private Attributes
double marker_lo_offset
double marker_hi_offset
Detailed Description
Definition at line 60 of file soda_wfall.hpp.
Constructor & Destructor Documentation
WFall()
GUISoDa::WFall::WFall (QWidget * parent = 0) explicit
Definition at line 139 of file soda_wfall.cpp.
References initPlot().
~WFall()
GUISoDa::WFall::~WFall ()
Definition at line 145 of file soda_wfall.cpp.
Member Function Documentation
configureSpectrum
void GUISoDa::WFall::configureSpectrum (double cfreq, double span, long buckets) inline slot
Definition at line 87 of file soda_wfall.hpp.
References setFreqCenter(), setMarkerOffset(), GUISoDa::WFallData::setSpectrumDimensions(), setZAxis(), spectrum_input_span, and wfall_data.
correctCenterFreq()
double GUISoDa::WFall::correctCenterFreq (double cfreq) protected
Definition at line 189 of file soda_wfall.cpp.
References freq_span, last_input_cfreq, and spectrum_input_span.
Referenced by setFreqCenter(), and setFreqSpan().
freqCenter()
double GUISoDa::WFall::freqCenter () inline
Definition at line 68 of file soda_wfall.hpp.
References center_freq, pickPoint(), setDynamicRange(), setFreqCenter(), setFreqMarker(), setFreqSpan(), setRefLevel(), and updateData().
initPlot()
void GUISoDa::WFall::initPlot () private
Definition at line 150 of file soda_wfall.cpp.
References freq_scale_p, freq_span, last_input_cfreq, picker_p, pickPoint(), right_axis, GUISoDa::PlotSpectrogram::setData(), setFreqCenter(), setMarkerOffset(), sgram, and wfall_data.
Referenced by WFall().
pickPoint
void GUISoDa::WFall::pickPoint (const QPointF & pos) slot
Definition at line 250 of file soda_wfall.cpp.
References marker_lo_offset, setFreqMarker(), and xClick().
Referenced by freqCenter(), and initPlot().
scrollLeft
void GUISoDa::WFall::scrollLeft (bool v) inline slot
Definition at line 84 of file soda_wfall.hpp.
References center_freq, freq_span, and setFreqCenter().
scrollRight
void GUISoDa::WFall::scrollRight (bool v) inline slot
Definition at line 80 of file soda_wfall.hpp.
References center_freq, freq_span, and setFreqCenter().
setDynamicRange
void GUISoDa::WFall::setDynamicRange (double drange) slot
Definition at line 257 of file soda_wfall.cpp.
References GUISoDa::WFallData::setDynamicRange(), setZAxis(), and wfall_data.
Referenced by freqCenter().
setFreqCenter
void GUISoDa::WFall::setFreqCenter (double cf, bool check_boundary = false) slot
Definition at line 200 of file soda_wfall.cpp.
References center_freq, correctCenterFreq(), freq_scale_p, freq_span, GUISoDa::PlotSpectrogram::rescan(), GUISoDa::FreqScaleDraw::setFreqStep(), and sgram.
Referenced by configureSpectrum(), freqCenter(), initPlot(), scrollLeft(), and scrollRight().
setFreqMarker
void GUISoDa::WFall::setFreqMarker (double freq) slot
Definition at line 244 of file soda_wfall.cpp.
References marker_freq, marker_hi_offset, marker_lo_offset, and setMarkers().
Referenced by freqCenter(), pickPoint(), and setMarkerOffset().
setFreqSpan
void GUISoDa::WFall::setFreqSpan (double fs, bool check_boundary = false) slot
Definition at line 212 of file soda_wfall.cpp.
References center_freq, correctCenterFreq(), freq_scale_p, freq_span, marker_freq, GUISoDa::PlotSpectrogram::rescan(), GUISoDa::FreqScaleDraw::setFreqStep(), and sgram.
Referenced by freqCenter(), and setFreqSpanKHz().
setFreqSpanKHz
void GUISoDa::WFall::setFreqSpanKHz (double fs) inline slot
Definition at line 79 of file soda_wfall.hpp.
References setFreqSpan().
setMarkerOffset
void GUISoDa::WFall::setMarkerOffset (double lo, double hi) slot
Definition at line 238 of file soda_wfall.cpp.
References marker_freq, marker_hi_offset, marker_lo_offset, and setFreqMarker().
Referenced by configureSpectrum(), and initPlot().
setMarkers()
void GUISoDa::WFall::setMarkers (double lo, double hi) inline private
Definition at line 97 of file soda_wfall.hpp.
References GUISoDa::WFallData::setMarkers(), and wfall_data.
Referenced by setFreqMarker().
setRefLevel
void GUISoDa::WFall::setRefLevel (int rlvl) slot
Definition at line 263 of file soda_wfall.cpp.
References GUISoDa::WFallData::setRefLevel(), setZAxis(), and wfall_data.
Referenced by freqCenter().
setZAxis()
void GUISoDa::WFall::setZAxis () private
Definition at line 269 of file soda_wfall.cpp.
References GUISoDa::PlotSpectrogram::rescan(), right_axis, sgram, and wfall_data.
Referenced by configureSpectrum(), setDynamicRange(), and setRefLevel().
updateData
void GUISoDa::WFall::updateData (double cf, float * y) slot
Definition at line 231 of file soda_wfall.cpp.
References last_input_cfreq, GUISoDa::WFallData::updateData(), and wfall_data.
Referenced by freqCenter().
xClick
void GUISoDa::WFall::xClick (double x) signal
Referenced by pickPoint(), and MainWindow::setupWaterFall().
Member Data Documentation
center_freq
double GUISoDa::WFall::center_freq protected
Definition at line 112 of file soda_wfall.hpp.
Referenced by freqCenter(), scrollLeft(), scrollRight(), setFreqCenter(), and setFreqSpan().
freq_scale_p
FreqScaleDraw* GUISoDa::WFall::freq_scale_p protected
Definition at line 124 of file soda_wfall.hpp.
Referenced by initPlot(), setFreqCenter(), and setFreqSpan().
freq_span
double GUISoDa::WFall::freq_span protected
Definition at line 113 of file soda_wfall.hpp.
Referenced by correctCenterFreq(), initPlot(), scrollLeft(), scrollRight(), setFreqCenter(), and setFreqSpan().
last_input_cfreq
double GUISoDa::WFall::last_input_cfreq protected
Definition at line 115 of file soda_wfall.hpp.
Referenced by correctCenterFreq(), initPlot(), and updateData().
marker_freq
double GUISoDa::WFall::marker_freq protected
Definition at line 116 of file soda_wfall.hpp.
Referenced by setFreqMarker(), setFreqSpan(), and setMarkerOffset().
marker_hi_offset
double GUISoDa::WFall::marker_hi_offset private
Definition at line 101 of file soda_wfall.hpp.
Referenced by setFreqMarker(), and setMarkerOffset().
marker_lo_offset
double GUISoDa::WFall::marker_lo_offset private
Definition at line 100 of file soda_wfall.hpp.
Referenced by pickPoint(), setFreqMarker(), and setMarkerOffset().
picker_p
WFallPicker* GUISoDa::WFall::picker_p protected
Definition at line 122 of file soda_wfall.hpp.
Referenced by initPlot().
right_axis
QwtScaleWidget* GUISoDa::WFall::right_axis protected
Definition at line 126 of file soda_wfall.hpp.
Referenced by initPlot(), and setZAxis().
sgram
PlotSpectrogram* GUISoDa::WFall::sgram protected
Definition at line 120 of file soda_wfall.hpp.
Referenced by initPlot(), setFreqCenter(), setFreqSpan(), and setZAxis().
spectrum_input_span
double GUISoDa::WFall::spectrum_input_span protected
Definition at line 114 of file soda_wfall.hpp.
Referenced by configureSpectrum(), and correctCenterFreq().
wfall_data
WFallData* GUISoDa::WFall::wfall_data protected
Definition at line 119 of file soda_wfall.hpp.
Referenced by configureSpectrum(), initPlot(), setDynamicRange(), setMarkers(), setRefLevel(), setZAxis(), and updateData().
The documentation for this class was generated from the following files:
qtgui/soda_wfall.hpp
qtgui/soda_wfall.cpp