SoDaRadio-5.0.1-master:9075e65: SoDa::GPS_TSIPmon Class Reference
SoDa::GPS_TSIPmon Class Reference
#include <GPS_TSIPmon.hxx>
Classes
class SoDaPrimaryTimingReport
class SoDaSuplementalTimingReport
Public Member Functions
GPS_TSIPmon (Params *params, CmdMBox *cmd_stream)
void run ()
Each thread object must define its "run" loop.
Public Member Functions inherited from SoDa::SoDaThread
SoDaThread (const std::string &oname)
void start ()
Execute the threads run loop.
void join ()
more properly "Wait for this thread to exit its run loop".
void execCommand (Command *cmd)
Execute (dispatch) a message removed from the command stream to one of the basic Command handler functions.
Public Member Functions inherited from SoDa::SoDaBase
SoDaBase (const std::string &oname)
The constructor – pass a name for the object.
std::string & getObjName ()
get the name of this object
SoDaBase * findSoDaObject (const std::string &oname)
find a SoDa Object by name.
double getTime ()
Get a time stamp in nS resolution that monotonically increases and that is very inexpensive (typically < 100nS).
Public Member Functions inherited from SoDa::Debug
Debug (std::string _unit_name=std::string("UNKNOWN"))
Debug (const char *_unit_name_cstr)
Debug (unsigned int _debug_level, std::string _unit_name=std::string("UNKNOWN"))
Debug (unsigned int _debug_level, const char *_unit_name_cstr)
void debugMsg (const std::string &msg, unsigned int threshold=1)
void debugMsg (const boost::format &fmt, unsigned int threshold=1)
void debugMsg (const char *msg, unsigned int threshold=1)
void setDebugLevel (unsigned int v)
unsigned int getDebugLevel ()
Private Member Functions
void execGetCommand (Command *cmd)
optional method to handle "GET" commands – commands that request a response
void execSetCommand (Command *cmd)
optional method to handle "SET" commands – commands that set internal state in the object.
void execRepCommand (Command *cmd)
optional method that reports status or the result of some action.
double curtime ()
Private Attributes
struct timeval basetime
CmdMBox * cmd_stream
unsigned int cmd_subs
SoDaPrimaryTimingReport * PTR_p
SoDaSuplementalTimingReport * STR_p
TSIP::Reader * TSIP_reader_p
Additional Inherited Members
Static Public Member Functions inherited from SoDa::Debug
static void setDefaultLevel (unsigned int v)
static unsigned int getDefaultLevel ()
static void setGlobalLevel (unsigned int v)
static unsigned int getGlobalLevel ()
Static Public Attributes inherited from SoDa::Debug
static boost::mutex debug_msg_mutex
Protected Member Functions inherited from SoDa::Debug
std::string curDateTime ()
Protected Attributes inherited from SoDa::Debug
std::string unit_name
the name of the unit reporting status
unsigned int debug_level
the debug level (threshold) for messages
Static Protected Attributes inherited from SoDa::Debug
static unsigned int default_debug_level = 0
static unsigned int global_debug_level = 0
Detailed Description
Definition at line 43 of file GPS_TSIPmon.hxx.
Constructor & Destructor Documentation
GPS_TSIPmon()
SoDa::GPS_TSIPmon::GPS_TSIPmon (Params * params, CmdMBox * cmd_stream)
Definition at line 33 of file GPS_TSIPmon.cxx.
References cmd_stream, cmd_subs, PTR_p, STR_p, SoDa::MultiMBox< T >::subscribe(), and TSIP_reader_p.
Member Function Documentation
curtime()
double SoDa::GPS_TSIPmon::curtime () inline private
Definition at line 54 of file GPS_TSIPmon.hxx.
References basetime.
execGetCommand()
void SoDa::GPS_TSIPmon::execGetCommand (Command * cmd) private virtual
optional method to handle "GET" commands – commands that request a response
Reimplemented from SoDa::SoDaThread.
Definition at line 71 of file GPS_TSIPmon.cxx.
execRepCommand()
void SoDa::GPS_TSIPmon::execRepCommand (Command * cmd) private virtual
optional method that reports status or the result of some action.
Reimplemented from SoDa::SoDaThread.
Definition at line 83 of file GPS_TSIPmon.cxx.
execSetCommand()
void SoDa::GPS_TSIPmon::execSetCommand (Command * cmd) private virtual
optional method to handle "SET" commands – commands that set internal state in the object.
Reimplemented from SoDa::SoDaThread.
Definition at line 77 of file GPS_TSIPmon.cxx.
run()
void SoDa::GPS_TSIPmon::run () virtual
Each thread object must define its "run" loop.
This loop exits only when the thread has received a STOP command on one of its command mailboxes.
Implements SoDa::SoDaThread.
Definition at line 48 of file GPS_TSIPmon.cxx.
References cmd_stream, cmd_subs, SoDa::SoDaThread::execCommand(), SoDa::MultiMBox< T >::free(), SoDa::MultiMBox< T >::get(), TSIP::Reader::readStream(), SoDa::Command::STOP, SoDa::Command::target, TSIP_reader_p, and TSIP::Report::updateStatus().
Member Data Documentation
basetime
struct timeval SoDa::GPS_TSIPmon::basetime private
Definition at line 53 of file GPS_TSIPmon.hxx.
Referenced by curtime().
cmd_stream
CmdMBox* SoDa::GPS_TSIPmon::cmd_stream private
Definition at line 60 of file GPS_TSIPmon.hxx.
Referenced by GPS_TSIPmon(), and run().
cmd_subs
unsigned int SoDa::GPS_TSIPmon::cmd_subs private
Definition at line 61 of file GPS_TSIPmon.hxx.
Referenced by GPS_TSIPmon(), and run().
PTR_p
SoDaPrimaryTimingReport* SoDa::GPS_TSIPmon::PTR_p private
Definition at line 93 of file GPS_TSIPmon.hxx.
Referenced by GPS_TSIPmon().
STR_p
SoDaSuplementalTimingReport* SoDa::GPS_TSIPmon::STR_p private
Definition at line 94 of file GPS_TSIPmon.hxx.
Referenced by GPS_TSIPmon().
TSIP_reader_p
TSIP::Reader* SoDa::GPS_TSIPmon::TSIP_reader_p private
Definition at line 96 of file GPS_TSIPmon.hxx.
Referenced by GPS_TSIPmon(), and run().
The documentation for this class was generated from the following files:
src/GPS_TSIPmon.hxx
src/GPS_TSIPmon.cxx