SoDaRadio-5.0.3-master:8901fb5: GUISoDa::LogTable Class Reference
GUISoDa::LogTable Class Reference
#include <soda_logtable.hpp>
Public Slots
void logContact (const QString &from_call, const QString &from_grid, const QString &to_call, const QString &to_grid, const QString &mode, const QString &comment, double rx_freq, double tx_freq)
void setKeys (QStringList headers)
void setLogFile (const QString &fname)
void writeLogReport (const QString &fname)
void readLogReport (const QString &fname)
void writeLogReportDlg ()
void readLogReportDlg ()
Signals
void entryUpdated (int row, const QString &key, const QString &val)
Public Member Functions
LogTable (QWidget *parent=Q_NULLPTR)
~LogTable ()
Protected Slots
void recordChange (int r, int c)
Protected Member Functions
void openLogFile ()
void readLogFile (const QString &fname)
void recordEdit (int row, int col)
bool emptyRow (int r)
void setField (int row, const QString &key_st, const QString &st)
void setField (int row, const QString &key_st, double val)
Protected Attributes
int next_used_row
QStringList current_headers
QFile * log_file_out
Detailed Description
Definition at line 45 of file soda_logtable.hpp.
Constructor & Destructor Documentation
LogTable()
GUISoDa::LogTable::LogTable (QWidget * parent = Q_NULLPTR) explicit
Definition at line 38 of file soda_logtable.cpp.
References current_headers, entryUpdated(), log_file_out, next_used_row, recordChange(), setKeys(), and setLogFile().
~LogTable()
GUISoDa::LogTable::~LogTable ()
Definition at line 79 of file soda_logtable.cpp.
References log_file_out.
Member Function Documentation
emptyRow()
bool GUISoDa::LogTable::emptyRow (int r) protected
Definition at line 94 of file soda_logtable.cpp.
Referenced by writeLogReport().
entryUpdated
void GUISoDa::LogTable::entryUpdated (int row, const QString & key, const QString & val) signal
Referenced by LogTable().
logContact
void GUISoDa::LogTable::logContact (const QString & from_call, const QString & from_grid, const QString & to_call, const QString & to_grid, const QString & mode, const QString & comment, double rx_freq, double tx_freq) slot
Definition at line 191 of file soda_logtable.cpp.
References next_used_row, and setField().
openLogFile()
void GUISoDa::LogTable::openLogFile () protected
readLogFile()
void GUISoDa::LogTable::readLogFile (const QString & fname) protected
readLogReport
void GUISoDa::LogTable::readLogReport (const QString & fname) slot
Definition at line 140 of file soda_logtable.cpp.
References next_used_row.
Referenced by readLogReportDlg().
readLogReportDlg
void GUISoDa::LogTable::readLogReportDlg () slot
Definition at line 172 of file soda_logtable.cpp.
References readLogReport().
recordChange
void GUISoDa::LogTable::recordChange (int r, int c) protected slot
Definition at line 124 of file soda_logtable.cpp.
References log_file_out.
Referenced by LogTable().
recordEdit()
void GUISoDa::LogTable::recordEdit (int row, int col) protected
setField() [1/2]
void GUISoDa::LogTable::setField (int row, const QString & key_st, const QString & st) inline protected
Definition at line 87 of file soda_logtable.hpp.
Referenced by logContact().
setField() [2/2]
void GUISoDa::LogTable::setField (int row, const QString & key_st, double val) inline protected
Definition at line 96 of file soda_logtable.hpp.
setKeys
void GUISoDa::LogTable::setKeys (QStringList headers) slot
Definition at line 73 of file soda_logtable.cpp.
References current_headers.
Referenced by LogTable().
setLogFile
void GUISoDa::LogTable::setLogFile (const QString & fname) slot
Definition at line 223 of file soda_logtable.cpp.
References log_file_out.
Referenced by LogTable(), and writeLogReport().
writeLogReport
void GUISoDa::LogTable::writeLogReport (const QString & fname) slot
Definition at line 101 of file soda_logtable.cpp.
References emptyRow(), log_file_out, and setLogFile().
Referenced by writeLogReportDlg().
writeLogReportDlg
void GUISoDa::LogTable::writeLogReportDlg () slot
Definition at line 181 of file soda_logtable.cpp.
References writeLogReport().
Member Data Documentation
current_headers
QStringList GUISoDa::LogTable::current_headers protected
Definition at line 107 of file soda_logtable.hpp.
Referenced by LogTable(), and setKeys().
log_file_out
QFile* GUISoDa::LogTable::log_file_out protected
Definition at line 109 of file soda_logtable.hpp.
Referenced by LogTable(), recordChange(), setLogFile(), writeLogReport(), and ~LogTable().
next_used_row
int GUISoDa::LogTable::next_used_row protected
Definition at line 106 of file soda_logtable.hpp.
Referenced by logContact(), LogTable(), and readLogReport().
The documentation for this class was generated from the following files:
qtgui/soda_logtable.hpp
qtgui/soda_logtable.cpp