SoDaRadio-5.0.1-master:9075e65: TSIP::Report Class Reference
TSIP::Report Class Reference abstract
#include <TSIP.hxx>
Public Member Functions
Report ()
virtual bool parseBuf (unsigned char *buf, int buflen)=0
virtual bool updateStatus ()=0
Detailed Description
Definition at line 55 of file TSIP.hxx.
Constructor & Destructor Documentation
Report()
TSIP::Report::Report () inline
Definition at line 57 of file TSIP.hxx.
References parseBuf(), and updateStatus().
Member Function Documentation
parseBuf()
virtual bool TSIP::Report::parseBuf (unsigned char * buf, int buflen) pure virtual
Implemented in TSIP::SuplementalTimingReport, and TSIP::PrimaryTimingReport.
Referenced by TSIP::PrimaryTimingReport::PrimaryTimingReport(), Report(), and TSIP::SuplementalTimingReport::SuplementalTimingReport().
updateStatus()
virtual bool TSIP::Report::updateStatus () pure virtual
Implemented in TSIP::SuplementalTimingReport, TSIP::PrimaryTimingReport, SoDa::GPS_TSIPmon::SoDaSuplementalTimingReport, and SoDa::GPS_TSIPmon::SoDaPrimaryTimingReport.
Referenced by main(), TSIP::PrimaryTimingReport::PrimaryTimingReport(), Report(), SoDa::GPS_TSIPmon::run(), and TSIP::SuplementalTimingReport::SuplementalTimingReport().
The documentation for this class was generated from the following file:
src/TSIP.hxx