SoDaRadio-5.0.1-master:9075e65: GUISoDa::FreqScaleDraw Class Reference
GUISoDa::FreqScaleDraw Class Reference
#include <soda_freq_scale_draw.hpp>
Public Member Functions
FreqScaleDraw ()
void setFreqStep (double cf, double st)
virtual QwtText label (double f) const override
Protected Attributes
double center_freq
double freq_step
Detailed Description
Definition at line 37 of file soda_freq_scale_draw.hpp.
Constructor & Destructor Documentation
FreqScaleDraw()
GUISoDa::FreqScaleDraw::FreqScaleDraw () inline explicit
Definition at line 40 of file soda_freq_scale_draw.hpp.
References center_freq.
Member Function Documentation
label()
virtual QwtText GUISoDa::FreqScaleDraw::label (double f) const inline override virtual
Definition at line 46 of file soda_freq_scale_draw.hpp.
References center_freq, and freq_step.
setFreqStep()
void GUISoDa::FreqScaleDraw::setFreqStep (double cf, double st) inline
Definition at line 44 of file soda_freq_scale_draw.hpp.
References center_freq, and freq_step.
Referenced by GUISoDa::Spect::replotXAxis(), GUISoDa::WFall::setFreqCenter(), and GUISoDa::WFall::setFreqSpan().
Member Data Documentation
center_freq
double GUISoDa::FreqScaleDraw::center_freq protected
Definition at line 58 of file soda_freq_scale_draw.hpp.
Referenced by FreqScaleDraw(), label(), and setFreqStep().
freq_step
double GUISoDa::FreqScaleDraw::freq_step protected
Definition at line 59 of file soda_freq_scale_draw.hpp.
Referenced by label(), and setFreqStep().
The documentation for this class was generated from the following file:
qtgui/soda_freq_scale_draw.hpp