SoDaRadio-5.0.3-master:8901fb5: GUISoDa::Spect Class Reference
GUISoDa::Spect Class Reference
#include <soda_spect.hpp>
Public Slots
void updateData (double cfreq, float *y)
void pickPoint (const QPointF &pos)
void setDynamicRange (double drange)
void setRefLevel (int rlvl)
void setFreqCenter (double cf, bool check_boundary=false)
void setFreqSpan (double fs, bool check_boundary=false)
void setFreqSpanKHz (double fs)
void setFreqMarker (double f)
void scrollRight (bool v)
void scrollLeft (bool v)
void configureSpectrum (double cfreq, double span, long buckets)
void setMarkerOffset (double lo, double hi)
Signals
void xClick (double x)
Public Member Functions
Spect (QWidget *parent=0)
~Spect ()
double freqCenter ()
Protected Member Functions
void resetFreqAxis (double cfreq)
void replotXAxis ()
void replotYAxis ()
double correctCenterFreq (double cfreq)
Protected Attributes
double * freqs
double * vals
int num_buckets
double center_freq_in
double freq_span_in
double center_freq_disp
double freq_span_disp
double val_ref
double val_range
double marker_lo_offset
double marker_hi_offset
double marker_freq
FreqScaleDraw * freq_draw_p
QwtPlotCurve * curve_p
PlotPicker * picker_p
QwtPlotGrid * grid_p
QwtPlotShapeItem freq_marker
Private Member Functions
void initPlot ()
Detailed Description
Definition at line 49 of file soda_spect.hpp.
Constructor & Destructor Documentation
Spect()
GUISoDa::Spect::Spect (QWidget * parent = 0) explicit
Definition at line 39 of file soda_spect.cpp.
References initPlot().
~Spect()
GUISoDa::Spect::~Spect ()
Definition at line 45 of file soda_spect.cpp.
References freqs, num_buckets, and vals.
Member Function Documentation
configureSpectrum
void GUISoDa::Spect::configureSpectrum (double cfreq, double span, long buckets) slot
Definition at line 214 of file soda_spect.cpp.
References center_freq_in, freq_span_in, freqs, marker_freq, num_buckets, resetFreqAxis(), setFreqCenter(), and vals.
Referenced by scrollLeft().
correctCenterFreq()
double GUISoDa::Spect::correctCenterFreq (double cfreq) protected
Definition at line 156 of file soda_spect.cpp.
References center_freq_in, freq_span_disp, and freq_span_in.
Referenced by scrollLeft(), and setFreqSpan().
freqCenter()
double GUISoDa::Spect::freqCenter () inline
Definition at line 57 of file soda_spect.hpp.
References center_freq_disp, pickPoint(), setDynamicRange(), setFreqCenter(), setFreqSpan(), setRefLevel(), and updateData().
initPlot()
void GUISoDa::Spect::initPlot () private
Definition at line 53 of file soda_spect.cpp.
References curve_p, freq_draw_p, freq_marker, freq_span_disp, freqs, grid_p, num_buckets, picker_p, pickPoint(), setFreqCenter(), setRefLevel(), val_ref, and vals.
Referenced by Spect().
pickPoint
void GUISoDa::Spect::pickPoint (const QPointF & pos) slot
Definition at line 180 of file soda_spect.cpp.
References marker_lo_offset, setFreqMarker(), and xClick().
Referenced by freqCenter(), and initPlot().
replotXAxis()
void GUISoDa::Spect::replotXAxis () protected
Definition at line 134 of file soda_spect.cpp.
References center_freq_disp, freq_draw_p, freq_span_disp, and GUISoDa::FreqScaleDraw::setFreqStep().
Referenced by scrollLeft(), setFreqCenter(), and setFreqSpan().
replotYAxis()
void GUISoDa::Spect::replotYAxis () protected
Definition at line 122 of file soda_spect.cpp.
References val_range, and val_ref.
Referenced by scrollLeft(), setDynamicRange(), and setRefLevel().
resetFreqAxis()
void GUISoDa::Spect::resetFreqAxis (double cfreq) protected
Definition at line 204 of file soda_spect.cpp.
References freq_span_in, freqs, and num_buckets.
Referenced by configureSpectrum(), scrollLeft(), and updateData().
scrollLeft
void GUISoDa::Spect::scrollLeft (bool v) inline slot
Definition at line 73 of file soda_spect.hpp.
References center_freq_disp, configureSpectrum(), correctCenterFreq(), freq_span_disp, replotXAxis(), replotYAxis(), resetFreqAxis(), setFreqCenter(), setMarkerOffset(), and xClick().
scrollRight
void GUISoDa::Spect::scrollRight (bool v) inline slot
Definition at line 69 of file soda_spect.hpp.
References center_freq_disp, freq_span_disp, and setFreqCenter().
setDynamicRange
void GUISoDa::Spect::setDynamicRange (double drange) slot
Definition at line 116 of file soda_spect.cpp.
References replotYAxis(), and val_range.
Referenced by freqCenter().
setFreqCenter
void GUISoDa::Spect::setFreqCenter (double cf, bool check_boundary = false) slot
Definition at line 148 of file soda_spect.cpp.
References center_freq_disp, and replotXAxis().
Referenced by configureSpectrum(), freqCenter(), initPlot(), scrollLeft(), and scrollRight().
setFreqMarker
void GUISoDa::Spect::setFreqMarker (double f) slot
Definition at line 194 of file soda_spect.cpp.
References freq_marker, marker_freq, marker_hi_offset, and marker_lo_offset.
Referenced by pickPoint(), setFreqSpanKHz(), and setMarkerOffset().
setFreqSpan
void GUISoDa::Spect::setFreqSpan (double fs, bool check_boundary = false) slot
Definition at line 167 of file soda_spect.cpp.
References center_freq_disp, correctCenterFreq(), freq_span_disp, marker_freq, and replotXAxis().
Referenced by freqCenter(), and setFreqSpanKHz().
setFreqSpanKHz
void GUISoDa::Spect::setFreqSpanKHz (double fs) inline slot
Definition at line 66 of file soda_spect.hpp.
References setFreqMarker(), and setFreqSpan().
setMarkerOffset
void GUISoDa::Spect::setMarkerOffset (double lo, double hi) slot
Definition at line 187 of file soda_spect.cpp.
References marker_freq, marker_hi_offset, marker_lo_offset, and setFreqMarker().
Referenced by scrollLeft().
setRefLevel
void GUISoDa::Spect::setRefLevel (int rlvl) slot
Definition at line 110 of file soda_spect.cpp.
References replotYAxis(), and val_ref.
Referenced by freqCenter(), and initPlot().
updateData
void GUISoDa::Spect::updateData (double cfreq, float * y) slot
Definition at line 102 of file soda_spect.cpp.
References center_freq_in, curve_p, freqs, num_buckets, resetFreqAxis(), and vals.
Referenced by freqCenter().
xClick
void GUISoDa::Spect::xClick (double x) signal
Referenced by pickPoint(), and scrollLeft().
Member Data Documentation
center_freq_disp
double GUISoDa::Spect::center_freq_disp protected
Definition at line 108 of file soda_spect.hpp.
Referenced by freqCenter(), replotXAxis(), scrollLeft(), scrollRight(), setFreqCenter(), and setFreqSpan().
center_freq_in
double GUISoDa::Spect::center_freq_in protected
Definition at line 103 of file soda_spect.hpp.
Referenced by configureSpectrum(), correctCenterFreq(), and updateData().
curve_p
QwtPlotCurve* GUISoDa::Spect::curve_p protected
Definition at line 124 of file soda_spect.hpp.
Referenced by initPlot(), and updateData().
freq_draw_p
FreqScaleDraw* GUISoDa::Spect::freq_draw_p protected
Definition at line 122 of file soda_spect.hpp.
Referenced by initPlot(), and replotXAxis().
freq_marker
QwtPlotShapeItem GUISoDa::Spect::freq_marker protected
Definition at line 130 of file soda_spect.hpp.
Referenced by initPlot(), and setFreqMarker().
freq_span_disp
double GUISoDa::Spect::freq_span_disp protected
Definition at line 109 of file soda_spect.hpp.
Referenced by correctCenterFreq(), initPlot(), replotXAxis(), scrollLeft(), scrollRight(), and setFreqSpan().
freq_span_in
double GUISoDa::Spect::freq_span_in protected
Definition at line 104 of file soda_spect.hpp.
Referenced by configureSpectrum(), correctCenterFreq(), and resetFreqAxis().
freqs
double* GUISoDa::Spect::freqs protected
Definition at line 97 of file soda_spect.hpp.
Referenced by configureSpectrum(), initPlot(), resetFreqAxis(), updateData(), and ~Spect().
grid_p
QwtPlotGrid* GUISoDa::Spect::grid_p protected
Definition at line 128 of file soda_spect.hpp.
Referenced by initPlot().
marker_freq
double GUISoDa::Spect::marker_freq protected
Definition at line 120 of file soda_spect.hpp.
Referenced by configureSpectrum(), setFreqMarker(), setFreqSpan(), and setMarkerOffset().
marker_hi_offset
double GUISoDa::Spect::marker_hi_offset protected
Definition at line 117 of file soda_spect.hpp.
Referenced by setFreqMarker(), and setMarkerOffset().
marker_lo_offset
double GUISoDa::Spect::marker_lo_offset protected
Definition at line 116 of file soda_spect.hpp.
Referenced by pickPoint(), setFreqMarker(), and setMarkerOffset().
num_buckets
int GUISoDa::Spect::num_buckets protected
Definition at line 99 of file soda_spect.hpp.
Referenced by configureSpectrum(), initPlot(), resetFreqAxis(), updateData(), and ~Spect().
picker_p
PlotPicker* GUISoDa::Spect::picker_p protected
Definition at line 126 of file soda_spect.hpp.
Referenced by initPlot().
val_range
double GUISoDa::Spect::val_range protected
Definition at line 113 of file soda_spect.hpp.
Referenced by replotYAxis(), and setDynamicRange().
val_ref
double GUISoDa::Spect::val_ref protected
Definition at line 112 of file soda_spect.hpp.
Referenced by initPlot(), replotYAxis(), and setRefLevel().
vals
double* GUISoDa::Spect::vals protected
Definition at line 98 of file soda_spect.hpp.
Referenced by configureSpectrum(), initPlot(), updateData(), and ~Spect().
The documentation for this class was generated from the following files:
qtgui/soda_spect.hpp
qtgui/soda_spect.cpp