SoDaRadio-5.0.1-master:9075e65: GUISoDa::FreqLabel Class Reference
GUISoDa::FreqLabel Class Reference
#include <freqlabel.hpp>
Public Slots
void setFreq (double freq)
Signals
void newFreq (double freq)
Public Member Functions
FreqLabel (QWidget *parent=Q_NULLPTR, Qt::WindowFlags f=Qt::WindowFlags())
~FreqLabel ()
double getFreq () const
void setFreqUpdate (double freq)
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
double updateFrequency ()
Private Member Functions
QString freq2String ()
Private Attributes
double frequency
long int_freq
long frac_freq
int incdec_position
int disp_w
int disp_h
Detailed Description
Definition at line 40 of file freqlabel.hpp.
Constructor & Destructor Documentation
FreqLabel()
GUISoDa::FreqLabel::FreqLabel (QWidget * parent = Q_NULLPTR, Qt::WindowFlags f = Qt::WindowFlags()) explicit
Definition at line 35 of file freqlabel.cpp.
References setFreq().
~FreqLabel()
GUISoDa::FreqLabel::~FreqLabel ()
Definition at line 45 of file freqlabel.cpp.
Member Function Documentation
freq2String()
QString GUISoDa::FreqLabel::freq2String () private
Definition at line 47 of file freqlabel.cpp.
References frac_freq, incdec_position, and int_freq.
Referenced by setFreq().
getFreq()
double GUISoDa::FreqLabel::getFreq () const inline
Definition at line 49 of file freqlabel.hpp.
References frequency.
mousePressEvent()
void GUISoDa::FreqLabel::mousePressEvent (QMouseEvent * event) protected
Definition at line 108 of file freqlabel.cpp.
References frac_freq, frequency, incdec_position, int_freq, newFreq(), setFreq(), and updateFrequency().
Referenced by setFreqUpdate().
newFreq
void GUISoDa::FreqLabel::newFreq (double freq) signal
Referenced by mousePressEvent(), and setFreqUpdate().
setFreq
void GUISoDa::FreqLabel::setFreq (double freq) slot
Definition at line 90 of file freqlabel.cpp.
References disp_h, disp_w, frac_freq, freq2String(), frequency, and int_freq.
Referenced by FreqLabel(), mousePressEvent(), and setFreqUpdate().
setFreqUpdate()
void GUISoDa::FreqLabel::setFreqUpdate (double freq) inline
Definition at line 53 of file freqlabel.hpp.
References frequency, mousePressEvent(), newFreq(), and setFreq().
updateFrequency()
double GUISoDa::FreqLabel::updateFrequency () inline protected
Definition at line 66 of file freqlabel.hpp.
References frac_freq, frequency, and int_freq.
Referenced by mousePressEvent().
Member Data Documentation
disp_h
int GUISoDa::FreqLabel::disp_h private
Definition at line 81 of file freqlabel.hpp.
Referenced by setFreq().
disp_w
int GUISoDa::FreqLabel::disp_w private
Definition at line 81 of file freqlabel.hpp.
Referenced by setFreq().
frac_freq
long GUISoDa::FreqLabel::frac_freq private
Definition at line 75 of file freqlabel.hpp.
Referenced by freq2String(), mousePressEvent(), setFreq(), and updateFrequency().
frequency
double GUISoDa::FreqLabel::frequency private
Definition at line 74 of file freqlabel.hpp.
Referenced by getFreq(), mousePressEvent(), setFreq(), setFreqUpdate(), and updateFrequency().
incdec_position
int GUISoDa::FreqLabel::incdec_position private
Definition at line 79 of file freqlabel.hpp.
Referenced by freq2String(), and mousePressEvent().
int_freq
long GUISoDa::FreqLabel::int_freq private
Definition at line 75 of file freqlabel.hpp.
Referenced by freq2String(), mousePressEvent(), setFreq(), and updateFrequency().
The documentation for this class was generated from the following files:
qtgui/freqlabel.hpp
qtgui/freqlabel.cpp