SoDaRadio-5.0.1-master:9075e65: SoDa::AudioALSA Class Reference
SoDa::AudioALSA Class Reference
ALSA audio interface class.
#include <AudioALSA.hxx>
Public Member Functions
AudioALSA (unsigned int _sample_rate, AudioIfc::DataFormat _fmt, unsigned int _sample_count_hint=1024, std::string audio_port_name=std::string("default"))
constructor
~AudioALSA ()
int send (void *buf, unsigned int len)
send – send a buffer to the audio output
bool sendBufferReady (unsigned int len)
sendBufferReady – is there enough space in the audio device send buffer for a call from send?
int recv (void *buf, unsigned int len, bool block=true)
recv – get a buffer of data from the audio input
bool recvBufferReady (unsigned int len)
recvBufferReady – are there samples waiting in the audio device?
void sleepOut ()
stop the output stream so that we don't encounter a buffer underflow while the reciever is muted.
void wakeOut ()
start the output stream
void sleepIn ()
stop the input stream so that we don't encounter a buffer overflow while the transmitter is inactive.
void wakeIn ()
start the input stream
Public Member Functions inherited from SoDa::AudioIfc
AudioIfc (unsigned int _sample_rate, DataFormat _fmt, unsigned int _sample_count_hint, const std::string &name="AudioIfc")
virtual bool setOutGain (float gain)
set the gain for the output device.
virtual bool setInGain (float gain)
set the gain for the input device.
virtual float getOutGain ()
get the gain for the output device.
virtual float getInGain ()
get the gain for the input device.
virtual std::string currentPlaybackState ()
virtual std::string currentCaptureState ()
Public Member Functions inherited from SoDa::SoDaBase
SoDaBase (const std::string &oname)
The constructor – pass a name for the object.
std::string & getObjName ()
get the name of this object
SoDaBase * findSoDaObject (const std::string &oname)
find a SoDa Object by name.
double getTime ()
Get a time stamp in nS resolution that monotonically increases and that is very inexpensive (typically < 100nS).
Additional Inherited Members
Public Types inherited from SoDa::AudioIfc
enum DataFormat {
FLOAT, DFLOAT, INT32, INT16,
INT8
}
Protected Attributes inherited from SoDa::AudioIfc
unsigned int sample_rate
DataFormat format
unsigned int sample_count_hint
float in_gain
float out_gain
int datatype_size
Detailed Description
ALSA audio interface class.
AudioALSA implements the interface specified by AudioIfc. It should be interchangable with other audio interface handlers.
The first several generations of SoDa used a Port Audio interface, but the PA library tends to spew a lot of extraneous "informational" messages on the console. Though it is quite simple, the noise that PA creates makes it not my (kb1vc) interface of choice.
ALSA on the other hand is documented poorly, organized oddly, and nearly inscrutable. But it is fast, and doesn't make a lot of noise on the console.
Definition at line 63 of file AudioALSA.hxx.
Constructor & Destructor Documentation
AudioALSA()
SoDa::AudioALSA::AudioALSA (unsigned int _sample_rate, AudioIfc::DataFormat _fmt, unsigned int _sample_count_hint = 1024, std::string audio_port_name = std::string("default"))
constructor
Parameters
_sample_rate in Hz 48000 is a good choice
_fmt the format of the data (FLOAT, DFLOAT, INT32, INT16, INT8)
_sample_count_hint the size of the buffers passed to and from the audio device (in samples)
audio_port_name which ALSA device are we connecting to?
Definition at line 255 of file AudioALSA.cxx.
~AudioALSA()
SoDa::AudioALSA::~AudioALSA () inline
Definition at line 78 of file AudioALSA.hxx.
Member Function Documentation
recv()
int SoDa::AudioALSA::recv (void * buf, unsigned int len, bool block = true) inline virtual
recv – get a buffer of data from the audio input
Parameters
buf buffer of type described by the DataFormat selected at init
len number of elements in the buffer to get
block make this a blocking call — ignored.
Returns
number of elements transferred from the audio input
Implements SoDa::AudioIfc.
Definition at line 107 of file AudioALSA.hxx.
recvBufferReady()
bool SoDa::AudioALSA::recvBufferReady (unsigned int len) inline virtual
recvBufferReady – are there samples waiting in the audio device?
Parameters
len the number of samples that we wish to get
Returns
true if len samples are waiting in in the device buffer
Implements SoDa::AudioIfc.
Definition at line 115 of file AudioALSA.hxx.
send()
int SoDa::AudioALSA::send (void * buf, unsigned int len) inline virtual
send – send a buffer to the audio output
Parameters
buf buffer of type described by the DataFormat selected at init
len number of elements in the buffer to send
Returns
number of elements transferred to the audio output
Implements SoDa::AudioIfc.
Definition at line 90 of file AudioALSA.hxx.
sendBufferReady()
bool SoDa::AudioALSA::sendBufferReady (unsigned int len) inline virtual
sendBufferReady – is there enough space in the audio device send buffer for a call from send?
Parameters
len the number of samples that we wish to send
Returns
true if there is sufficient space.
Implements SoDa::AudioIfc.
Definition at line 98 of file AudioALSA.hxx.
sleepIn()
void SoDa::AudioALSA::sleepIn () inline virtual
stop the input stream so that we don't encounter a buffer overflow while the transmitter is inactive.
Implements SoDa::AudioIfc.
Definition at line 149 of file AudioALSA.hxx.
sleepOut()
void SoDa::AudioALSA::sleepOut () inline virtual
stop the output stream so that we don't encounter a buffer underflow while the reciever is muted.
Implements SoDa::AudioIfc.
Definition at line 121 of file AudioALSA.hxx.
wakeIn()
void SoDa::AudioALSA::wakeIn () inline virtual
start the input stream
Implements SoDa::AudioIfc.
Definition at line 169 of file AudioALSA.hxx.
References SoDa::AudioIfc::currentCaptureState(), SoDa::AudioIfc::currentPlaybackState(), and SoDa::SoDaBase::getObjName().
wakeOut()
void SoDa::AudioALSA::wakeOut () inline virtual
start the output stream
Implements SoDa::AudioIfc.
Definition at line 129 of file AudioALSA.hxx.
The documentation for this class was generated from the following files:
src/AudioALSA.hxx
src/AudioALSA.cxx