SoDaRadio-5.0.3-master:8901fb5: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.hpp>
Public Slots
void setRXFreq (double freq)
set the RX frequency label to freq, and send the requested frequency to the SDR radio server.
void setTXFreq (double freq)
set the TX frequency label to freq, and send the requested frequency to the SDR radio server.
void updateBandDisplay (double freq)
void changeBand (const QString &band)
void writeBandMapEntry (bool)
void fillBandMapEntry (const QString &band)
void handleFatalError (const QString &err_string)
pop up a notification box and then bail out.
void logContact (bool)
log the current contact by storing the grid, call, date, time, frequency, mode, and other stuff into the log object.
void evalNav (const QString &dummy)
void updateTime (int h, int m, int s)
void updatePosition (double lat, double lon)
void restoreSettings ()
void saveConfig ()
void saveConfigAs_dlg ()
void restoreConfig_dlg ()
void displayAppInfo (bool dummy)
Public Member Functions
MainWindow (QWidget *parent, SoDa::GuiParams &params)
~MainWindow ()
Protected Member Functions
void setupTopControls ()
void setupMidControls ()
void setupLogGPS ()
void setupSettings ()
void setupBandConfig ()
void setupLogEditor ()
void setupWaterFall ()
void setupSpectrum ()
void setupHamlib ()
void widgetSaveRestore (QObject *op, const QString &par, bool save)
void bandMapSaveRestore (GUISoDa::BandMap &bmap, bool save)
void saveCurrentFreqs ()
void sendCannedCW (const QString &txt)
Private Member Functions
void closeEvent (QCloseEvent *event)
void setRXFreq_nocross (double freq)
void setTXFreq_nocross (double freq)
Private Attributes
QSettings * settings_p
GUISoDa::BandMap band_map
QString current_band_selector
QString auto_bandswitch_target
Ui::MainWindow * ui
GUISoDa::Listener * listener
GUISoDa::HamlibServer * hlib_server
Detailed Description
Definition at line 44 of file mainwindow.hpp.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent, SoDa::GuiParams & params)
Definition at line 47 of file mainwindow.cpp.
References auto_bandswitch_target, current_band_selector, displayAppInfo(), handleFatalError(), hlib_server, GUISoDa::Listener::init(), listener, GUISoDa::Listener::repHWMBVersion(), restoreSettings(), settings_p, setupBandConfig(), setupHamlib(), setupLogEditor(), setupLogGPS(), setupMidControls(), setupSettings(), setupSpectrum(), setupTopControls(), setupWaterFall(), GUISoDa::Listener::start(), GUISoDa::HamlibServer::start(), and ui.
~MainWindow()
MainWindow::~MainWindow ()
Definition at line 99 of file mainwindow.cpp.
References saveConfig(), and ui.
Member Function Documentation
bandMapSaveRestore()
void MainWindow::bandMapSaveRestore (GUISoDa::BandMap & bmap, bool save) protected
Definition at line 85 of file main_setup_bandconfig.cpp.
References GUISoDa::BandMap::restoreBands(), GUISoDa::BandMap::saveBands(), saveCurrentFreqs(), settings_p, and ui.
Referenced by restoreSettings(), and saveConfig().
changeBand
void MainWindow::changeBand (const QString & band) slot
Definition at line 190 of file main_setup_bandconfig.cpp.
References auto_bandswitch_target, band_map, current_band_selector, listener, saveCurrentFreqs(), setRXFreq(), GUISoDa::Listener::setSpectrumCenter(), setTXFreq(), and ui.
Referenced by setupBandConfig().
closeEvent()
void MainWindow::closeEvent (QCloseEvent * event) inline private
Definition at line 132 of file mainwindow.hpp.
displayAppInfo
void MainWindow::displayAppInfo (bool dummy) slot
Definition at line 105 of file mainwindow.cpp.
Referenced by MainWindow().
evalNav
void MainWindow::evalNav (const QString & dummy) slot
Definition at line 54 of file main_setup_loggps.cpp.
References ui.
Referenced by setupLogGPS().
fillBandMapEntry
void MainWindow::fillBandMapEntry (const QString & band) slot
Definition at line 110 of file main_setup_bandconfig.cpp.
References band_map, GUISoDa::Band::defMode(), GUISoDa::Band::defRXAnt(), GUISoDa::Band::defTXAnt(), GUISoDa::Band::index(), GUISoDa::Band::maxFreq(), GUISoDa::Band::minFreq(), GUISoDa::Band::tverterEna(), GUISoDa::Band::tverterLowInjection(), GUISoDa::Band::tvLOFreq(), GUISoDa::Band::tvLOMult(), GUISoDa::Band::txEna(), and ui.
Referenced by setupBandConfig().
handleFatalError
void MainWindow::handleFatalError (const QString & err_string) slot
pop up a notification box and then bail out.
Parameters
err_string a descriptive message explaining how we got here.
Definition at line 357 of file mainwindow.cpp.
Referenced by MainWindow().
logContact
void MainWindow::logContact (bool dummy) slot
log the current contact by storing the grid, call, date, time, frequency, mode, and other stuff into the log object.
Definition at line 73 of file main_setup_loggps.cpp.
References ui.
Referenced by setupLogGPS().
restoreConfig_dlg
void MainWindow::restoreConfig_dlg () slot
Definition at line 88 of file main_setup_settings.cpp.
References restoreSettings(), and settings_p.
Referenced by setupSettings().
restoreSettings
void MainWindow::restoreSettings () slot
Definition at line 349 of file mainwindow.cpp.
References band_map, bandMapSaveRestore(), settings_p, and widgetSaveRestore().
Referenced by MainWindow(), and restoreConfig_dlg().
saveConfig
void MainWindow::saveConfig () slot
Definition at line 68 of file main_setup_settings.cpp.
References band_map, bandMapSaveRestore(), settings_p, and widgetSaveRestore().
Referenced by saveConfigAs_dlg(), setupSettings(), and ~MainWindow().
saveConfigAs_dlg
void MainWindow::saveConfigAs_dlg () slot
Definition at line 76 of file main_setup_settings.cpp.
References saveConfig(), and settings_p.
Referenced by setupSettings().
saveCurrentFreqs()
void MainWindow::saveCurrentFreqs () protected
Definition at line 70 of file main_setup_bandconfig.cpp.
References band_map, current_band_selector, GUISoDa::Band::minFreq(), and ui.
Referenced by bandMapSaveRestore(), and changeBand().
sendCannedCW()
void MainWindow::sendCannedCW (const QString & txt) protected
Definition at line 135 of file main_setup_mid.cpp.
References listener, GUISoDa::Listener::sendCW(), and ui.
Referenced by setupMidControls().
setRXFreq
void MainWindow::setRXFreq (double freq) slot
set the RX frequency label to freq, and send the requested frequency to the SDR radio server.
Update markers in spectrum plots.
This function is called on updates to the RX frequency widget in the GUI or from the hamlib listener process.
This function will update the TX frequency iff the TX-RX lock switch is set.
Parameters
freq the new RX frequency.
Definition at line 73 of file main_setup_top.cpp.
References setRXFreq_nocross(), setTXFreq_nocross(), and ui.
Referenced by changeBand(), setupHamlib(), setupSpectrum(), setupTopControls(), and setupWaterFall().
setRXFreq_nocross()
void MainWindow::setRXFreq_nocross (double freq) private
Definition at line 110 of file main_setup_top.cpp.
References listener, GUISoDa::Listener::setRXFreq(), and ui.
Referenced by setRXFreq(), and setTXFreq().
setTXFreq
void MainWindow::setTXFreq (double freq) slot
set the TX frequency label to freq, and send the requested frequency to the SDR radio server.
Update markers in spectrum plots.
This function is called on updates to the TX frequency widget in the GUI or from the hamlib listener process.
This function will update the RX frequency iff the TX-RX lock switch is set.
Parameters
freq the new TX frequency.
Definition at line 81 of file main_setup_top.cpp.
References setRXFreq_nocross(), setTXFreq_nocross(), and ui.
Referenced by changeBand(), setupHamlib(), and setupTopControls().
setTXFreq_nocross()
void MainWindow::setTXFreq_nocross (double freq) private
Definition at line 126 of file main_setup_top.cpp.
References listener, GUISoDa::Listener::setTXFreq(), and ui.
Referenced by setRXFreq(), and setTXFreq().
setupBandConfig()
void MainWindow::setupBandConfig () protected
Definition at line 40 of file main_setup_bandconfig.cpp.
References GUISoDa::Listener::addRXAntName(), GUISoDa::Listener::addTXAntName(), changeBand(), fillBandMapEntry(), listener, ui, and writeBandMapEntry().
Referenced by MainWindow().
setupHamlib()
void MainWindow::setupHamlib () protected
Definition at line 36 of file main_setup_hamlib.cpp.
References GUISoDa::HamlibServer::getHandler(), hlib_server, listener, setRXFreq(), setTXFreq(), ui, and updateBandDisplay().
Referenced by MainWindow().
setupLogEditor()
void MainWindow::setupLogEditor () protected
Definition at line 36 of file main_setup_logeditor.cpp.
Referenced by MainWindow().
setupLogGPS()
void MainWindow::setupLogGPS () protected
Definition at line 37 of file main_setup_loggps.cpp.
References evalNav(), listener, logContact(), ui, updatePosition(), and updateTime().
Referenced by MainWindow().
setupMidControls()
void MainWindow::setupMidControls () protected
Definition at line 36 of file main_setup_mid.cpp.
References GUISoDa::Listener::addRXAntName(), GUISoDa::Listener::addTXAntName(), listener, GUISoDa::Listener::repPTT(), sendCannedCW(), and ui.
Referenced by MainWindow().
setupSettings()
void MainWindow::setupSettings () protected
Definition at line 36 of file main_setup_settings.cpp.
References listener, restoreConfig_dlg(), saveConfig(), saveConfigAs_dlg(), and ui.
Referenced by MainWindow().
setupSpectrum()
void MainWindow::setupSpectrum () protected
Definition at line 76 of file main_setup_spect.cpp.
References listener, setRXFreq(), and ui.
Referenced by MainWindow().
setupTopControls()
void MainWindow::setupTopControls () protected
Definition at line 36 of file main_setup_top.cpp.
References listener, setRXFreq(), setTXFreq(), and ui.
Referenced by MainWindow().
setupWaterFall()
void MainWindow::setupWaterFall () protected
Definition at line 39 of file main_setup_spect.cpp.
References listener, setRXFreq(), GUISoDa::Listener::setRXFreq(), ui, and GUISoDa::WFall::xClick().
Referenced by MainWindow().
updateBandDisplay
void MainWindow::updateBandDisplay (double freq) slot
Definition at line 87 of file main_setup_top.cpp.
References auto_bandswitch_target, band_map, GUISoDa::BandMap::findBand(), listener, GUISoDa::Listener::setSpectrumCenter(), and ui.
Referenced by setupHamlib().
updatePosition
void MainWindow::updatePosition (double lat, double lon) slot
Definition at line 92 of file main_setup_loggps.cpp.
References ui.
Referenced by setupLogGPS().
updateTime
void MainWindow::updateTime (int h, int m, int s) slot
Definition at line 86 of file main_setup_loggps.cpp.
References ui.
Referenced by setupLogGPS().
widgetSaveRestore()
void MainWindow::widgetSaveRestore (QObject * op, const QString & par, bool save) protected
Definition at line 147 of file mainwindow.cpp.
References settings_p.
Referenced by restoreSettings(), and saveConfig().
writeBandMapEntry
void MainWindow::writeBandMapEntry (bool v) slot
Definition at line 138 of file main_setup_bandconfig.cpp.
References band_map, GUISoDa::Band::setDefMode(), GUISoDa::Band::setDefRXAnt(), GUISoDa::Band::setDefTXAnt(), GUISoDa::Band::setIndex(), GUISoDa::Band::setLastRXFreq(), GUISoDa::Band::setLastTXFreq(), GUISoDa::Band::setMaxFreq(), GUISoDa::Band::setMinFreq(), GUISoDa::Band::setName(), GUISoDa::Band::setTverterEna(), GUISoDa::Band::setTverterLowInjection(), GUISoDa::Band::setTvLOFreq(), GUISoDa::Band::setTvLOMult(), GUISoDa::Band::setTxEna(), and ui.
Referenced by setupBandConfig().
Member Data Documentation
auto_bandswitch_target
QString MainWindow::auto_bandswitch_target private
Definition at line 144 of file mainwindow.hpp.
Referenced by changeBand(), MainWindow(), and updateBandDisplay().
band_map
GUISoDa::BandMap MainWindow::band_map private
Definition at line 141 of file mainwindow.hpp.
Referenced by changeBand(), fillBandMapEntry(), restoreSettings(), saveConfig(), saveCurrentFreqs(), updateBandDisplay(), and writeBandMapEntry().
current_band_selector
QString MainWindow::current_band_selector private
Definition at line 143 of file mainwindow.hpp.
Referenced by changeBand(), MainWindow(), and saveCurrentFreqs().
hlib_server
GUISoDa::HamlibServer* MainWindow::hlib_server private
Definition at line 153 of file mainwindow.hpp.
Referenced by MainWindow(), and setupHamlib().
listener
GUISoDa::Listener* MainWindow::listener private
Definition at line 151 of file mainwindow.hpp.
Referenced by changeBand(), MainWindow(), sendCannedCW(), setRXFreq_nocross(), setTXFreq_nocross(), setupBandConfig(), setupHamlib(), setupLogGPS(), setupMidControls(), setupSettings(), setupSpectrum(), setupTopControls(), setupWaterFall(), and updateBandDisplay().
settings_p
QSettings* MainWindow::settings_p private
Definition at line 137 of file mainwindow.hpp.
Referenced by bandMapSaveRestore(), MainWindow(), restoreConfig_dlg(), restoreSettings(), saveConfig(), saveConfigAs_dlg(), and widgetSaveRestore().
ui
Ui::MainWindow* MainWindow::ui private
Definition at line 149 of file mainwindow.hpp.
Referenced by bandMapSaveRestore(), changeBand(), evalNav(), fillBandMapEntry(), logContact(), MainWindow(), saveCurrentFreqs(), sendCannedCW(), setRXFreq(), setRXFreq_nocross(), setTXFreq(), setTXFreq_nocross(), setupBandConfig(), setupHamlib(), setupLogGPS(), setupMidControls(), setupSettings(), setupSpectrum(), setupTopControls(), setupWaterFall(), updateBandDisplay(), updatePosition(), updateTime(), writeBandMapEntry(), and ~MainWindow().
The documentation for this class was generated from the following files:
qtgui/mainwindow.hpp
qtgui/main_setup_bandconfig.cpp
qtgui/main_setup_hamlib.cpp
qtgui/main_setup_logeditor.cpp
qtgui/main_setup_loggps.cpp
qtgui/main_setup_mid.cpp
qtgui/main_setup_settings.cpp
qtgui/main_setup_spect.cpp
qtgui/main_setup_top.cpp
qtgui/mainwindow.cpp