SoDaRadio-5.0.1-master:9075e65: SoDa::UD::ServerSocket Class Reference
SoDa::UD::ServerSocket Class Reference
#include <UDSockets.hxx>
Public Member Functions
ServerSocket (const std::string &path)
~ServerSocket ()
bool isReady ()
int get (void *ptr, unsigned int size)
int put (const void *ptr, unsigned int size)
Public Member Functions inherited from SoDa::UD::NetSocket
NetSocket ()
int put (const void *ptr, unsigned int size)
int get (void *ptr, unsigned int size)
Private Attributes
bool ready
std::string mailbox_pathname
Additional Inherited Members
Public Attributes inherited from SoDa::UD::NetSocket
int server_socket
int conn_socket
int portnum
struct sockaddr_un server_address client_address
struct timeval timeout
Detailed Description
Definition at line 65 of file UDSockets.hxx.
Constructor & Destructor Documentation
ServerSocket()
SoDa::UD::ServerSocket::ServerSocket (const std::string & path)
Definition at line 44 of file UDSockets.cxx.
References mailbox_pathname, ready, and SoDa::UD::NetSocket::server_socket.
~ServerSocket()
SoDa::UD::ServerSocket::~ServerSocket () inline
Definition at line 68 of file UDSockets.hxx.
References SoDa::UD::NetSocket::conn_socket, and SoDa::UD::NetSocket::server_socket.
Member Function Documentation
get()
int SoDa::UD::ServerSocket::get (void * ptr, unsigned int size) inline
Definition at line 75 of file UDSockets.hxx.
References SoDa::UD::NetSocket::get().
Referenced by main(), and SoDa::UI::run().
isReady()
bool SoDa::UD::ServerSocket::isReady ()
Definition at line 119 of file UDSockets.cxx.
References SoDa::UD::NetSocket::client_address, SoDa::UD::NetSocket::conn_socket, ready, and SoDa::UD::NetSocket::server_socket.
Referenced by main(), SoDa::UI::run(), and SoDa::UI::sendFFT().
put()
int SoDa::UD::ServerSocket::put (const void * ptr, unsigned int size) inline
Definition at line 80 of file UDSockets.hxx.
References SoDa::UD::NetSocket::put().
Referenced by main(), SoDa::UI::reportSpectrumCenterFreq(), SoDa::UI::run(), and SoDa::UI::sendFFT().
Member Data Documentation
mailbox_pathname
std::string SoDa::UD::ServerSocket::mailbox_pathname private
Definition at line 88 of file UDSockets.hxx.
Referenced by ServerSocket().
ready
bool SoDa::UD::ServerSocket::ready private
Definition at line 87 of file UDSockets.hxx.
Referenced by isReady(), and ServerSocket().
The documentation for this class was generated from the following files:
src/UDSockets.hxx
src/UDSockets.cxx