SoDaRadio-5.0.1-master:9075e65: SoDa::IP::ServerSocket Class Reference
SoDa::IP::ServerSocket Class Reference
#include <IPSockets.hxx>
Public Member Functions
ServerSocket (int portnum, TransportType transport=TCP)
~ServerSocket ()
bool isReady ()
int get (void *ptr, unsigned int size)
int put (const void *ptr, unsigned int size)
Public Member Functions inherited from SoDa::IP::NetSocket
NetSocket ()
int put (const void *ptr, unsigned int size)
int get (void *ptr, unsigned int size)
int putRaw (const void *ptr, unsigned int size)
int getRaw (const void *ptr, unsigned int size, unsigned int usec_timeout=0)
get a raw string of <size> bytes...
void setNonBlocking ()
void setBlocking ()
Protected Attributes
bool ready
Additional Inherited Members
Public Attributes inherited from SoDa::IP::NetSocket
int server_socket
int conn_socket
int portnum
struct sockaddr_in server_address client_address
bool non_blocking_mode
struct timeval timeout
Detailed Description
Definition at line 102 of file IPSockets.hxx.
Constructor & Destructor Documentation
ServerSocket()
SoDa::IP::ServerSocket::ServerSocket (int portnum, TransportType transport = TCP)
Definition at line 43 of file IPSockets.cxx.
References ready, SoDa::IP::NetSocket::server_socket, SoDa::IP::TCP, and SoDa::IP::UDP.
~ServerSocket()
SoDa::IP::ServerSocket::~ServerSocket () inline
Definition at line 105 of file IPSockets.hxx.
Member Function Documentation
get()
int SoDa::IP::ServerSocket::get (void * ptr, unsigned int size) inline
Definition at line 108 of file IPSockets.hxx.
References SoDa::IP::NetSocket::get().
Referenced by main().
isReady()
bool SoDa::IP::ServerSocket::isReady ()
Definition at line 119 of file IPSockets.cxx.
References SoDa::IP::NetSocket::client_address, SoDa::IP::NetSocket::conn_socket, ready, and SoDa::IP::NetSocket::server_socket.
Referenced by SoDa::IP::LineServerSocket::getLine(), and main().
put()
int SoDa::IP::ServerSocket::put (const void * ptr, unsigned int size) inline
Definition at line 113 of file IPSockets.hxx.
References SoDa::IP::NetSocket::put().
Referenced by main().
Member Data Documentation
ready
bool SoDa::IP::ServerSocket::ready protected
Definition at line 120 of file IPSockets.hxx.
Referenced by SoDa::IP::LineServerSocket::getLine(), isReady(), and ServerSocket().
The documentation for this class was generated from the following files:
src/IPSockets.hxx
src/IPSockets.cxx