SoDaRadio-5.0.3-master:8901fb5: SoDa::UD::NetSocket Class Reference
SoDa::UD::NetSocket Class Reference
#include <UDSockets.hxx>
Public Member Functions
NetSocket ()
int put (const void *ptr, unsigned int size)
int get (void *ptr, unsigned int size)
Public Attributes
int server_socket
int conn_socket
int portnum
struct sockaddr_un server_address client_address
struct timeval timeout
Private Member Functions
int loopWrite (int fd, const void *ptr, unsigned int nbytes)
Detailed Description
Definition at line 46 of file UDSockets.hxx.
Constructor & Destructor Documentation
NetSocket()
SoDa::UD::NetSocket::NetSocket () inline
Definition at line 48 of file UDSockets.hxx.
References put(), and timeout.
Member Function Documentation
get()
int SoDa::UD::NetSocket::get (void * ptr, unsigned int size)
Definition at line 175 of file UDSockets.cxx.
References conn_socket.
Referenced by SoDa::UD::ServerSocket::get(), and main().
loopWrite()
int SoDa::UD::NetSocket::loopWrite (int fd, const void * ptr, unsigned int nbytes) private
Definition at line 140 of file UDSockets.cxx.
Referenced by put().
put()
int SoDa::UD::NetSocket::put (const void * ptr, unsigned int size)
Definition at line 162 of file UDSockets.cxx.
References conn_socket, and loopWrite().
Referenced by main(), NetSocket(), and SoDa::UD::ServerSocket::put().
Member Data Documentation
client_address
struct sockaddr_un server_address SoDa::UD::NetSocket::client_address
Definition at line 58 of file UDSockets.hxx.
Referenced by SoDa::UD::ServerSocket::isReady().
conn_socket
int SoDa::UD::NetSocket::conn_socket
Definition at line 57 of file UDSockets.hxx.
Referenced by SoDa::UD::ClientSocket::ClientSocket(), get(), SoDa::UD::ServerSocket::isReady(), put(), SoDa::UD::ClientSocket::~ClientSocket(), and SoDa::UD::ServerSocket::~ServerSocket().
portnum
int SoDa::UD::NetSocket::portnum
Definition at line 57 of file UDSockets.hxx.
server_socket
int SoDa::UD::NetSocket::server_socket
Definition at line 57 of file UDSockets.hxx.
Referenced by SoDa::UD::ServerSocket::isReady(), SoDa::UD::ServerSocket::ServerSocket(), and SoDa::UD::ServerSocket::~ServerSocket().
timeout
struct timeval SoDa::UD::NetSocket::timeout
Definition at line 60 of file UDSockets.hxx.
Referenced by NetSocket().
The documentation for this class was generated from the following files:
src/UDSockets.hxx
src/UDSockets.cxx