SoDaRadio-5.0.3-master:8901fb5: GUISoDa::PlotSpectrogram Class Reference
GUISoDa::PlotSpectrogram Class Reference
Public Member Functions
PlotSpectrogram ()
~PlotSpectrogram ()
void setData (QwtRasterData *dp)
void rescan ()
Protected Member Functions
QImage renderImage (const QwtScaleMap &xMap, const QwtScaleMap &yMap, const QRectF &area, const QSize &imageSize) const
Protected Attributes
QSize lastSize
QImage saved_image
bool rescan_required
QwtRasterData * data_p
Detailed Description
Definition at line 72 of file soda_wfall.cpp.
Constructor & Destructor Documentation
PlotSpectrogram()
GUISoDa::PlotSpectrogram::PlotSpectrogram () inline explicit
Definition at line 75 of file soda_wfall.cpp.
~PlotSpectrogram()
GUISoDa::PlotSpectrogram::~PlotSpectrogram () inline
Definition at line 79 of file soda_wfall.cpp.
Member Function Documentation
renderImage()
QImage GUISoDa::PlotSpectrogram::renderImage (const QwtScaleMap & xMap, const QwtScaleMap & yMap, const QRectF & area, const QSize & imageSize) const inline protected
Definition at line 92 of file soda_wfall.cpp.
rescan()
void GUISoDa::PlotSpectrogram::rescan () inline
Definition at line 87 of file soda_wfall.cpp.
Referenced by GUISoDa::WFall::setFreqCenter(), GUISoDa::WFall::setFreqSpan(), and GUISoDa::WFall::setZAxis().
setData()
void GUISoDa::PlotSpectrogram::setData (QwtRasterData * dp) inline
Definition at line 82 of file soda_wfall.cpp.
Referenced by GUISoDa::WFall::initPlot().
Member Data Documentation
data_p
QwtRasterData* GUISoDa::PlotSpectrogram::data_p protected
Definition at line 136 of file soda_wfall.cpp.
lastSize
QSize GUISoDa::PlotSpectrogram::lastSize mutable protected
Definition at line 133 of file soda_wfall.cpp.
rescan_required
bool GUISoDa::PlotSpectrogram::rescan_required mutable protected
Definition at line 135 of file soda_wfall.cpp.
saved_image
QImage GUISoDa::PlotSpectrogram::saved_image mutable protected
Definition at line 134 of file soda_wfall.cpp.
The documentation for this class was generated from the following file:
qtgui/soda_wfall.cpp