SoDaRadio-5.0.3-master:8901fb5: GUISoDa::HamlibListener Class Reference
GUISoDa::HamlibListener Class Reference
#include <soda_hamlib_listener.hpp>
Public Slots
void readyRead ()
void disconnected ()
void setFinished ()
Signals
void error (QTcpSocket::SocketError err)
Public Member Functions
HamlibListener (qintptr desc, HamlibHandler *_handler, QObject *parent=0)
void run ()
Protected Attributes
HamlibHandler * handler_p
qintptr socket_desc
QString current_command
QTcpSocket * socket_p
Detailed Description
Definition at line 38 of file soda_hamlib_listener.hpp.
Constructor & Destructor Documentation
HamlibListener()
GUISoDa::HamlibListener::HamlibListener (qintptr desc, GUISoDa::HamlibHandler * _handler, QObject * parent = 0) explicit
Definition at line 33 of file soda_hamlib_listener.cpp.
Member Function Documentation
disconnected
void GUISoDa::HamlibListener::disconnected () slot
Definition at line 74 of file soda_hamlib_listener.cpp.
References socket_p.
Referenced by run().
error
void GUISoDa::HamlibListener::error (QTcpSocket::SocketError err) signal
Referenced by run().
readyRead
void GUISoDa::HamlibListener::readyRead () slot
Definition at line 57 of file soda_hamlib_listener.cpp.
References current_command, handler_p, GUISoDa::HamlibHandler::processCommand(), and socket_p.
Referenced by run().
run()
void GUISoDa::HamlibListener::run ()
Definition at line 42 of file soda_hamlib_listener.cpp.
References disconnected(), error(), readyRead(), socket_desc, and socket_p.
setFinished
void GUISoDa::HamlibListener::setFinished () inline slot
Definition at line 54 of file soda_hamlib_listener.hpp.
Member Data Documentation
current_command
QString GUISoDa::HamlibListener::current_command protected
Definition at line 59 of file soda_hamlib_listener.hpp.
Referenced by readyRead().
handler_p
HamlibHandler* GUISoDa::HamlibListener::handler_p protected
Definition at line 57 of file soda_hamlib_listener.hpp.
Referenced by readyRead().
socket_desc
qintptr GUISoDa::HamlibListener::socket_desc protected
Definition at line 58 of file soda_hamlib_listener.hpp.
Referenced by run().
socket_p
QTcpSocket* GUISoDa::HamlibListener::socket_p protected
Definition at line 60 of file soda_hamlib_listener.hpp.
Referenced by disconnected(), readyRead(), and run().
The documentation for this class was generated from the following files:
qtgui/soda_hamlib_listener.hpp
qtgui/soda_hamlib_listener.cpp