SoDaRadio-5.0.3-master:8901fb5: exp/FFT_Test.cxx File Reference
FFT_Test.cxx File Reference
#include <complex>
#include <iostream>
#include <stdlib.h>
#include <time.h>
#include <fftw3.h>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
Macros
#define SAMPLE_RATE 48000
Functions
double curtime ()
complex< float > doWork (complex< float > *in, complex< float > *out, unsigned int vsize)
int main (int argc, char *argv[])
Macro Definition Documentation
SAMPLE_RATE
#define SAMPLE_RATE 48000
Definition at line 28 of file FFT_Test.cxx.
Function Documentation
curtime()
double curtime ()
Definition at line 49 of file FFT_Test.cxx.
Referenced by doWork(), and main().
doWork()
complex<float> doWork (complex< float > * in, complex< float > * out, unsigned int vsize)
Definition at line 58 of file FFT_Test.cxx.
References curtime().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 87 of file FFT_Test.cxx.
References curtime(), and doWork().