SoDaRadio-5.0.3-master:8901fb5: n200serbabble Namespace Reference
n200serbabble Namespace Reference
Variables
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
string host = '192.168.10.2'
int port = 49172
tuple msg = ("ON00NO\r", "ST00TS\r")
int sel = 0
Variable Documentation
host
string n200serbabble.host = '192.168.10.2'
Definition at line 13 of file n200serbabble.py.
msg
tuple n200serbabble.msg = ("ON00NO\r", "ST00TS\r")
Definition at line 17 of file n200serbabble.py.
Referenced by SoDa::Debug.debugMsg(), SoDa::USRPCtrl.getUSRP(), and SoDaTest::MultiMBox_Test_Thread.run().
port
int n200serbabble.port = 49172
Definition at line 14 of file n200serbabble.py.
Referenced by SoDa::B200Control.B200Control().
sel
int n200serbabble.sel = 0
Definition at line 18 of file n200serbabble.py.
Referenced by GUISoDa::WFColorMap.WFColorMap().
sock
n200serbabble.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
Definition at line 8 of file n200serbabble.py.