SoDaRadio-5.0.3-master:8901fb5: SoDa Namespace Reference
SoDa Namespace Reference
Namespaces
IP
UD
Classes
class AudioALSA
ALSA audio interface class.
class AudioIfc
Generic Audio Interface Class.
class AudioPA
the PortAudio interface class
class B200Control
Transmit/Receive switch control for B200/B210 via the FX3 debug GPIO pins.
class BaseBandRX
BaseBandRX – this is the audio processing chain for the recieve path.
class BaseBandTX
class Command
This is a list of all the commands that can "do something" to one or more components in the SoDa radio.
class CWGenerator
A text to morse envelope converter.
class CWTX
The CW text-to-envelope converter run loop.
class Debug
A simple base class to provide debug messaging from any derived class.
class GPSmon
class HilbertTransformer
In several places we have a real valued signal x(t) that needs to be converted to an analytic signal g(t) such that real(g(t)) == x(t) and imag(g(t)) = shift_by_90degrees(x(t));.
class Histogram
A generic histogram widget.
class IntNTuner
This is a tuner for the UBX, WBX, or SBX module that takes advantage of the int_n_step argument in the tune request.
struct leftOfRange
class MBoxMessage
class MedianFilter3
3 point Median Filter class – templatized (!)
class MultiMBox
class N200Control
Transmit/Receive switch control for N200/N210 via the GPS serial or EXP serial io port.
class NoopControl
a null control class that returns happily for everyone.
class OSFilter
Overlap-and-save filter class.
class Params
This class handles command line parameters and built-ins.
class PropTree
PropTree class encapsulates the USRP property tree functions to allow better trap and error recovery management.
class QuadratureOscillator
sin/cos oscillator to drive TX signal chain
class Range
a template class for mapping ranges to thingies This represents an open interval – thanks to suggestions from http://stackoverflow.com/questions/1089192/c-stl-range-container
class RangeMap
class ReSample48to625
Resampler for 48KHz to 625KHz data stream, built on rational ReSampler class.
class ReSample625to48
Resampler for 625KHz to 48KHz data stream, built on rational ReSampler class.
class ReSampler
Rational Resampler.
class SerialDev
class SimpleTuner
This is a simple front end tuner.
class SoDaBase
The SoDa Base class.
class SoDaBuf
The Buffer Class.
class SoDaException
The SoDa Exception class.
class SoDaThread
The Thread baseclass for all SoDa thread objects.
class Spectrogram
Spectrogram generates magnitude buffers from input sample stream.
class TestServer
class TRControl
Generic Control class to activate T/R switching, band switching, and other control functions.
class UI
class USRPCtrl
Though libuhd is designed to be re-entrant, there are some indications that all control functions (set_freq, gain, and other operations) should originate from a single thread.
class USRPRX
The Receive RF Path.
class USRPTuner
Generic class for TX and RX tuning.
class USRPTX
The Transmit RF Path.
Typedefs
typedef MultiMBox< Command > CmdMBox
Mailboxes that carry commands only are of type CmdMBox.
typedef MultiMBox< SoDaBuf > DatMBox
Mailboxes that carry float or complex data are of type DatMBox.
Functions
PropTree * getUSRPFrontEnd (PropTree *tree, char tr_choice)
return a pointer to a PropTree object for the first "T" or "R" front end that provides an IQ or QI stream.
PropTree * getUSRPFrontEnd (PropTree &tree, char tr_choice)
return a pointer to a PropTree object for the first "T" or "R" front end that provides an IQ or QI stream.
Typedef Documentation
CmdMBox
typedef MultiMBox<Command> SoDa::CmdMBox
Mailboxes that carry commands only are of type CmdMBox.
Definition at line 151 of file SoDaBase.hxx.
DatMBox
typedef MultiMBox<SoDaBuf> SoDa::DatMBox
Mailboxes that carry float or complex data are of type DatMBox.
Definition at line 155 of file SoDaBase.hxx.
Function Documentation
getUSRPFrontEnd() [1/2]
PropTree * SoDa::getUSRPFrontEnd (PropTree * tree, char tr_choice)
return a pointer to a PropTree object for the first "T" or "R" front end that provides an IQ or QI stream.
Parameters
tree pointer to a PropTree root
tr_choice 'T', 't' for transmit, 'R', 'r' for receive.
Returns
PropTree object or NULL if none found
Definition at line 37 of file USRPFrontEnd.cxx.
References SoDa::PropTree::getPropNames(), and SoDa::PropTree::getStringProp().
Referenced by getUSRPFrontEnd(), main(), and SoDa::USRPCtrl::USRPCtrl().
getUSRPFrontEnd() [2/2]
PropTree * SoDa::getUSRPFrontEnd (PropTree & tree, char tr_choice)
return a pointer to a PropTree object for the first "T" or "R" front end that provides an IQ or QI stream.
Parameters
tree reference to a PropTree root
tr_choice 'T', 't' for transmit, 'R', 'r' for receive.
Returns
PropTree object or NULL if none found
Definition at line 72 of file USRPFrontEnd.cxx.
References getUSRPFrontEnd().