SoDaRadio-5.0.3-master:8901fb5: exp/TestServer.cxx File Reference
TestServer.cxx File Reference
#include <uhd/usrp/multi_usrp.hpp>
#include "SoDaBase.hxx"
#include "MultiMBox.hxx"
#include "Params.hxx"
#include "UI.hxx"
#include "Command.hxx"
Classes
class SoDa::TestServer
Namespaces
SoDa
Functions
int doWork (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
doWork()
int doWork (int argc, char * argv[])
Definition at line 76 of file TestServer.cxx.
References SoDa::TestServer::cmd_stream, SoDa::TestServer::cwtxt_stream, SoDa::SoDaThread::join(), and SoDa::SoDaThread::start().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 117 of file TestServer.cxx.
References doWork(), and SoDa::SoDaException::toString().